version: '3.8'

services:
  web:
    build: .
    container_name: projeto-api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
